AdminFarm/config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  #root 'welcome#index'
  devise_scope :user do
    root to: "users/sessions#new"
  end
  
  namespace :admin do
    #get '/' => 'welcome#index'
    resources :contacts
    resources :animal_sales
    resources :sale_types
    resources :animal_deaths
    resources :death_types
    resources :application_medicines
    resources :vaccinations
    resources :weighings
    resources :animals
    resources :animal_states
    resources :animal_stages
    resources :breed_animals
    resources :vaccines
    resources :medicines
    resources :animal_categories
    resources :farm_lots
    resources :farms
    resources :destinies
    resources :origins
    resources :genders
      resources :companies
  end
end

AdminFarm/app/models/contact.rb
class Contact < ApplicationRecord
  
  validates :name, :email, :message, presence: true
  validates :name, :email, :message, length: { minimum: 2 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :accept, :acceptance => true
  
 #:name, :email, :phone, :message, :accept, :newsletter, :info, :obs, :answered
    
end

AdminFarm/app/controllers/admin/contacts_controller.rb
module Admin
  class ContactsController < Admin::ApplicationController
    include ApplicationHelper
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Contact.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Contact.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

AdminFarm/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: :new

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        # format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        # format.html { redirect_to new_contact_path, notice: 'Contact was successfully created.' }
        format.html { redirect_to new_contact_path, notice: t('activerecord.successful.messages.created', :model => @contact.class.model_name)}
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message, :accept, :newsletter, :info, :obs, :answered)
    end
end

AdminFarm/app/helpers/contacts_helper.rb
module ContactsHelper
end

AdminFarm/app/views/contacts/_form.html.1.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :contact_phone %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :contact_message %>
  </div>

  <div class="field">
    <%= form.label :accept %>
    <%= form.check_box :accept, id: :contact_accept %>
  </div>

  <div class="field">
    <%= form.label :newsletter %>
    <%= form.check_box :newsletter, id: :contact_newsletter %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_field :info, id: :contact_info %>
  </div>

  <div class="field">
    <%= form.label :obs %>
    <%= form.text_field :obs, id: :contact_obs %>
  </div>

  <div class="field">
    <%= form.label :answered %>
    <%= form.check_box :answered, id: :contact_answered %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

AdminFarm/app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <div class="field">
    <%= form.label :name, class: 'label_form required' %>
    <%= form.text_field :name, id: :contact_name, autofocus: true, autocomplete: "name", placeholder: t(".name") %>
  </div>

  <div class="field">
    <%= form.label :email, class: 'label_form required' %>
    <%= form.text_field :email, id: :contact_email, autocomplete: "email", placeholder: t(".email")  %>
  </div>

  <div class="field">
    <%= form.label :phone, class: 'label_form' %>
    <%= form.text_field :phone, id: :contact_phone, autocomplete: "phone", placeholder: t(".phone")  %>
  </div>

  <div class="field">
    <%= form.label :message, class: 'label_form required' %>
    <%= form.text_area :message, id: :contact_message, autocomplete: "message", placeholder: t(".message")  %>
  </div>
  
  <div class="field">
    <%= form.check_box :accept, id: :contact_accept, class: "f" %>
    <%= form.label :accept %>
  </div>

  <div class="field">
    <%= form.check_box :newsletter, id: :contact_newsletter, class: "f" %>
    <%= form.label :newsletter %>
  </div>

  <div class="actions">
    <%= form.submit t(".send") %>
  </div>
<% end %>

AdminFarm/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

AdminFarm/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Message</th>
      <th>Accept</th>
      <th>Newsletter</th>
      <th>Info</th>
      <th>Obs</th>
      <th>Answered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.message %></td>
        <td><%= contact.accept %></td>
        <td><%= contact.newsletter %></td>
        <td><%= contact.info %></td>
        <td><%= contact.obs %></td>
        <td><%= contact.answered %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

AdminFarm/app/views/contacts/new.html.erb
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="margin-top:130px">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h1><%= t(".title") %></h1>
      
      <%= render 'form', contact: @contact %>
      
      <%= link_to t('.back'), contacts_path %>
    </div>
  </div>
</div>

AdminFarm/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<p>
  <strong>Accept:</strong>
  <%= @contact.accept %>
</p>

<p>
  <strong>Newsletter:</strong>
  <%= @contact.newsletter %>
</p>

<p>
  <strong>Info:</strong>
  <%= @contact.info %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @contact.obs %>
</p>

<p>
  <strong>Answered:</strong>
  <%= @contact.answered %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>