AdminFarm/config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  #root 'welcome#index'
  devise_scope :user do
    root to: "users/sessions#new"
  end
  
  namespace :admin do
    #get '/' => 'welcome#index'
    resources :contacts
    resources :animal_sales
    resources :sale_types
    resources :animal_deaths
    resources :death_types
    resources :application_medicines
    resources :vaccinations
    resources :weighings
    resources :animals
    resources :animal_states
    resources :animal_stages
    resources :breed_animals
    resources :vaccines
    resources :medicines
    resources :animal_categories
    resources :farm_lots
    resources :farms
    resources :destinies
    resources :origins
    resources :genders
      resources :companies
  end
end

AdminFarm/app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include ApplicationHelper
    
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end
    
    rescue_from ActiveRecord::DeleteRestrictionError do |exception|
      #redirect_to(redirect_back(fallback_location: root_path), :alert => exception.message)
      #redirect_back(fallback_location: root_path, :alert => exception.message )
      redirect_back(fallback_location: root_path, :alert => t("cannot.delete") )
      #redirect_back(fallback_location: root_path, :alert => t("cannot.delete", exception) )
    end
    
    # def show
    #   if not show_table('show', requested_resource.class).empty?
    #     show_table('show', requested_resource.class).each_with_index do |table, n|
    #       instance_variable_set("@table"+"#{n}", table.where(:gender_id => requested_resource).select(show_table1('show', requested_resource.class, table)).limit(10))
    #     end
    #   end  
    #   super
    # end  
    
    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

AdminFarm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

AdminFarm/app/helpers/application_helper.rb
module ApplicationHelper
  def show_table1(action, page, table)
    #Gender
    if (action = 'show' && page == Gender && table == AnimalStage)
        'id,animal_category_id,gender_id,name,min_month,max_month,obsolete'
    elsif (action = 'show' && page == Gender && table == AnimalState)
        'id,animal_category_id,gender_id,name,weigh_min,weigh_max,obsolete'
    elsif (action = 'show' && page == Gender && table == Animal)
        'id,animal_category_id,breed_animal_id,gender_id,animal_stage_id,animal_state_id,origin_id,farm_id,number_earring'
    #Origin
    elsif (action = 'show' && page == Origin && table == Animal)
        'id,animal_category_id,breed_animal_id,gender_id,animal_stage_id,animal_state_id,origin_id,farm_id,number_earring'
    #Destiny
    elsif (action = 'show' && page == Destiny && table == AnimalDeath)
        'id,animal_id,death_type_id,destiny_id,date_death,final_weigh'
    elsif (action = 'show' && page == Destiny && table == AnimalSale)
        'id,animal_id,sale_type_id,destiny_id,date_sale,purchase_value,sales_value,final_weigh'
    #Farm
    elsif (action = 'show' && page == Farm && table == FarmLot)
        'id,name,obsolete'
    #FarmLot
    elsif (action = 'show' && page == FarmLot && table == Farm)
        'id,name,address,obsolete'
    #AnimalCategory
    elsif (action = 'show' && page == AnimalCategory && table == Animal)
        'id,animal_category_id,breed_animal_id,gender_id,animal_stage_id,animal_state_id,origin_id,farm_id,number_earring'
    elsif (action = 'show' && page == AnimalCategory && table == BreedAnimal)
        'id,name,animal_category_id,name,obsolete'
    elsif (action = 'show' && page == AnimalCategory && table == AnimalStage)
        'id,animal_category_id,gender_id,name,min_month,max_month,obsolete'
    elsif (action = 'show' && page == AnimalCategory && table == AnimalState)
        'id,animal_category_id,gender_id,name,weigh_min,weigh_max,obsolete'
    elsif (action = 'show' && page == AnimalCategory && table == Medicine)
        'id,animal_category_id,name,obsolete'
    elsif (action = 'show' && page == AnimalCategory && table == Vaccine)
        'id,animal_category_id,name,obsolete'
    #Medicine
    elsif (action = 'show' && page == Medicine && table == ApplicationMedicine)
        'id,animal_id,medicine_id,date_medicine'
    #Vaccine
    elsif (action = 'show' && page == Vaccine && table == Vaccination)
        'id,animal_id,vaccine_id,date_vaccine'
    #BreedAnimal
    elsif (action = 'show' && page == BreedAnimal && table == AnimalCategory)
        'id,name,obsolete'    
    #AnimalStage
    elsif (action = 'show' && page == AnimalStage && table == Animal)
        'id,animal_category_id,breed_animal_id,gender_id,animal_stage_id,animal_state_id,origin_id,farm_id,number_earring'
    elsif (action = 'show' && page == AnimalStage && table == Weighing)
        'id,animal_stage_id,animal_state_id,weigh_date,weight,gain_weight,pregnant,sick'
    elsif (action = 'show' && page == AnimalStage && table == AnimalCategory)
        'id,name,obsolete' 
    elsif (action = 'show' && page == AnimalStage && table == Gender)
        'id,name,obsolete' 
    #AnimalState
    elsif (action = 'show' && page == AnimalState && table == Animal)
        'id,animal_category_id,breed_animal_id,gender_id,animal_stage_id,animal_state_id,origin_id,farm_id,number_earring'
    elsif (action = 'show' && page == AnimalState && table == Weighing)
        'id,animal_stage_id,animal_state_id,weigh_date,weight,gain_weight,pregnant,sick'
    elsif (action = 'show' && page == AnimalState && table == AnimalCategory)
        'id,name,obsolete' 
    elsif (action = 'show' && page == AnimalState && table == Gender)
        'id,name,obsolete' 
    #Animal
    elsif (action = 'show' && page == Animal && table == AnimalDeath)
        'id,death_type_id,destiny_id,date_death,final_weigh'
    elsif (action = 'show' && page == Animal && table == AnimalSale)
        'id,sale_type_id,destiny_id,date_sale,final_weigh'
    elsif (action = 'show' && page == Animal && table == Weighing)
        'id,animal_stage_id,animal_state_id,weigh_date,weight,gain_weight,pregnant,sick'
    elsif (action = 'show' && page == Animal && table == ApplicationMedicine)
        'id,medicine_id,date_medicine'
    else
      "gaga2"
    end
  end
  
  def attribute_name(model, field_name)
    if model == AnimalStage
      if (['animal_category_id','gender_id'].include? field_name) 
        :name
      end
    elsif model == AnimalState
      if (['animal_category_id','gender_id'].include? field_name) 
        :name
      end
    elsif model == Animal
      if (['animal_category_id','breed_animal_id','animal_stage_id','animal_state_id','origin_id','farm_id','gender_id'].include? field_name) 
        :name
      end
    elsif model == AnimalDeath
      if (['death_type_id','destiny_id'].include? field_name) 
        :name
      elsif (['animal_id'].include? field_name)
        :number_earring
      end
    elsif model == AnimalSale
      if (['sale_type_id','destiny_id'].include? field_name) 
        :name
      elsif (['animal_id'].include? field_name)
        :number_earring
      end
    elsif model == Weighing
      if (['animal_stage_id','animal_state_id'].include? field_name) 
        :name
      end
    elsif model == ApplicationMedicine
      if (['medicine_id'].include? field_name) 
        :name
      elsif (['animal_id'].include? field_name)
        :number_earring
      end
    elsif model == BreedAnimal
      if (['animal_category_id'].include? field_name) 
        :name
      end
    elsif model == Medicine
      if (['animal_category_id'].include? field_name) 
        :name
      end
    elsif model == Vaccine
      if (['animal_category_id'].include? field_name) 
        :name
      end
    elsif model == Vaccination
      if (['vaccine_id'].include? field_name) 
        :name
      elsif (['animal_id'].include? field_name)
        :number_earring
      end
    elsif model == AnimalCategory
      if (['animal_category_id'].include? field_name) 
        :name
      end
    else
      nil
    end
  end
  
  def t_get_boolean(value)
  	if (value == 'False' || value == 'false' || value == FalseClass || value == false)
  		t('boolean.false_')
  	elsif (value == 'True' || value == 'true' || value == TrueClass || value == true)
  		t('boolean.true_')
  	else
  		'teste'
  	end	
  end
  
  def show_table(action, page)
    if action == 'show'
      if page == Gender
        [AnimalStage, AnimalState, Animal]
      else
        []
      end
    end
  end
  
  def testeApp
    "testeApp"
  end
end

AdminFarm/app/views/admin/application/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% if defined? collection_presenter.filter_names != nil %>
  <%= t("administrate.filter.filters") %>:
  <% collection_presenter.filter_names.each do |key, value| %>
    <%= link_to( t("administrate.filter.#{value}"), "?search=#{key}", class: "button bt_teal", ) %>
  <% end %>
  <%= link_to( t("administrate.filter.no_filter"), "?search=", class: "button bt_orange") %> 
<% end %>

<% if defined? collection_presenter.index_actions != nil %>
  <br><br>
  <%= t("administrate.filter.actions") %>:
  <% collection_presenter.index_actions.each do |key, value| %>
    <%= link_to( "#{t("administrate.actions.new")} #{t(value['model'])}", [:new, namespace, value['link']], class: "button new") %>  
  <% end %>
  <br><br>
<% end %>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
      <th class="cell-label cell-label--<%= attr_type.html_class %> cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
          scope="col" role="columnheader" aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params.merge(collection_presenter.order_params_for(attr_name))) do %>
          <%= t("helpers.label.#{collection_presenter.resource_name}.#{attr_name}", default: attr_name.to_s,).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:show, collection_presenter.resource_name),
          valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
      <% if defined? collection_presenter.index_actions_linea != nil %> 
        <th>
          <%= t("administrate.filter.actions") %>
        </th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row" tabindex="0" <% if valid_action? :show, collection_presenter.resource_name %> <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <a href="<%= polymorphic_path([namespace, resource]) -%>"
               class="action-show">
              <%= render_field attribute if attribute.html_class != 'boolean'  %>
              <%#= t("#{attribute.html_class}.#{attribute}_", default: attribute) if attribute.html_class == 'boolean' %>
              <%= t_get_boolean(attribute.to_s) if attribute.html_class == 'boolean' %>
            </a>
          </td>
        <% end %>

        <% if valid_action? :show, collection_presenter.resource_name %>
          <td>
            <%= link_to(t("administrate.actions.show"), [namespace, resource], class: "button show") %>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td>
            <%= link_to(t("administrate.actions.edit"),[:edit, namespace, resource],class: "button edit") %>
          </td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td>
            <%= link_to( t("administrate.actions.destroy"), [namespace, resource], class: "button delete", method: :delete,data: { confirm: t("administrate.actions.confirm") }) %>
          </td>
        <% end %>
        
        <% if defined? collection_presenter.index_actions_linea != nil %> 
          <% collection_presenter.index_actions_linea.each do |key, value| %>
            <td>
              <%= link_to( "#{t("administrate.actions.new")} #{t(value['model'])}", {:controller => 'admin/'+ value['link'],:action => "new", value["parameter_name"] => resource.id}, {class: "button new button_#{resource.obsolete}"}) if valid_action? :new %>  
            </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

AdminFarm/app/views/admin/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value if key != "notice"  %>
        <%= t(value.split.first.downcase) if key == "notice" %><%= value.remove(value.split.first) if key == "notice" %>
      </div>
    <% end -%>
  </div>
<% end %>

AdminFarm/app/views/admin/application/_footer.html.erb
<footer>2019 © - Admin Farm - Developer: SouzaLeandror - <%= link_to "Link", admin_companies_path %></footer>

AdminFarm/app/views/admin/application/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%#= pluralize(page.resource.errors.count, "error") %>
        <!-- prohibited this <%#= page.resource_name %> from being saved: -->
        <%= t('errors.template.header.one', :model => "#{t(page.resource_name.titleize.downcase)}") if page.resource.errors.count == 1 %>
        <%= t('errors.template.header.other', :count => page.resource.errors.count, :model => "#{t(page.resource_name.titleize.downcase)}") if page.resource.errors.count != 1 %>
      </h2>
      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%#= f.submit %>
    <%= f.submit :class => (page.resource.new_record? ? 'new' : 'update') %>
  </div>
<% end %>

AdminFarm/app/views/admin/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.
%>

<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

AdminFarm/app/views/admin/application/_navbar.html.erb
<header>
  <div id="header-wrap">
    <h1><%= link_to "Admin Farm", root_path %></h1>
    <nav>
      <ul>
        <li class="button"><%= link_to t("menu.home"), root_path %></li>
        <li class="button"><%= link_to t("menu.signin"), new_user_session_path %></li>
        <li class="button"><%= link_to t("menu.signup"), new_user_registration_path %></li>
        <li class="button"><%= link_to t("menu.contact"), new_contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

AdminFarm/app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
    <%= link_to( display_resource_name(resource), [namespace, resource.path], class: "navigation__link navigation__link--#{nav_link_state(resource)}") %>
  <% end %>
</nav>

AdminFarm/app/views/admin/application/_show_tables.html.erb
<section class="main-content__body">
  <label class='f'>
    <%= link_to t(table.model_name.singular.downcase), [namespace, table.klass] %> - 
    <%= link_to( "#{t("administrate.actions.table.new")}", [:new, namespace, table.name.underscore]) if valid_action? :new %> - 
    <%= link_to( "#{t("administrate.actions.see_more")}", [:new, namespace, table.name.underscore]) if valid_action? :new %>
  </label>
  <table class="w3-table">
    <tr>
      <% show_table1('show', page.resource.class, table.klass).split(/,/).each do |field| %>
        <% if field.to_s != "id" %>
          <th><%= t("helpers.label.#{table.model_name.singular}.#{field}") %></th>
        <% end %>
      <% end %>
      <th><%= t("administrate.actions.table.actions") %></th>
    </tr>
    <% table.each do |t_field| %>
      <tr>
        <% show_table1('show', page.resource.class, table.klass).split(/,/).each do |field| %>
          <% if field.include? "_id" %>
            <td><%= t_field.send(field.gsub("_id", "")).read_attribute(attribute_name(t_field.class, field)) %></td>
          <% elsif field.include? "id" %>
            <% next %>
          <% else %>
            <% if (t_field.send(field).class == TrueClass || t_field.send(field).class == FalseClass) %>
              <td><%= t_get_boolean(t_field.send(field)) %></td>  
            <% else %>
              <td><%= t_field.send(field) %></td>
            <% end %>
          <% end %>
        <% end %>
        <td>
          <%= link_to("", [namespace, t_field], class: "button show icon_show") %>
          <%= link_to("", [:edit, namespace, t_field], class: "button edit icon_edit") %>
          <%= link_to("", [namespace, t_field], class: "button delete icon_delete", method: :delete, data: { confirm: t("administrate.actions.confirm") }) %>
        </td>
      </tr>
    <% end %>
  </table>
</section>

AdminFarm/app/views/admin/application/_stylesheet.html.erb
<%#
# Stylesheet Partial

This partial imports the necessary stylesheets on each page.
By default, it includes the application CSS,
but each page can define additional CSS sources
by providing a `content_for(:stylesheet)` block.
%>

<% Administrate::Engine.stylesheets.each do |css_path| %>
  <%= stylesheet_link_tag css_path %>
<% end %>

<%= yield :stylesheet %>

AdminFarm/app/views/admin/application/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "#{t("administrate.actions.edit")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>
  <div>
    <%= link_to( "#{t("administrate.actions.new")} #{t(page.resource_name.titleize.downcase)}",[:new, namespace, page.resource_path], class: "button new",) if valid_action? :new %>
    <%= link_to( "#{t("administrate.actions.show")} #{page.page_title}", [namespace, page.resource], class: "button show",) if valid_action? :show %>
    <%= link_to( "#{t("administrate.actions.destroy")} #{page.page_title}", [namespace, page.resource], class: "button delete", method: :delete, data: { confirm: t("administrate.actions.confirm") } ) %>
    <%= link_to( t("administrate.actions.list"), [namespace, page.resource.class], class: "button" )  %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

AdminFarm/app/views/admin/application/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <span>
      <%= link_to(content_for(:title), "?" ) %>
      <%#= content_for(:title) %> - <%= t("administrate.index.count_record") %>: <%= resources.count %>
    </span>
  </h1>
  <% if show_search_bar %>
    <%= render( "search", search_term: search_term, resource_name: display_resource_name(page.resource_name) ) %>
  <% end %>
  <div>
    <%= link_to( "#{t("administrate.actions.new")} #{t(page.resource_name.titleize.downcase)}", [:new, namespace, page.resource_path], class: "button new") if valid_action? :new %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render( "collection", collection_presenter: page, resources: resources, table_title: "page-title" ) %>
  <%= paginate resources %>
  <span>
      <br><br>
      <%= "#{t("administrate.exportation.dati")}" %>:
      <%= link_to("#{t("administrate.exportation.csv")}", "", class: "button exportation") %>
      <%= link_to("#{t("administrate.exportation.json")}", "", class: "button exportation") %>
      <%= link_to("#{t("administrate.exportation.xml")}", "", class: "button exportation") %>
      <%= link_to("#{t("administrate.exportation.excel")}", "", class: "button exportation") %>
      <%= link_to("#{t("administrate.exportation.pdf")}", "", class: "button exportation") %>
      <%= link_to("#{t("administrate.exportation.text")}", "", class: "button exportation") %>
      <%= link_to("#{t("administrate.exportation.seed")}", "", class: "button exportation") %>
      <%= link_to("#{t("administrate.exportation.sql")}", "", class: "button exportation") %>
  </span>
</section>

AdminFarm/app/views/admin/application/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "#{t("administrate.actions.new")} #{t(page.resource_name.titleize.downcase)}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %> 
  </h1>
  <div>
    <%#= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
  <div>
    <%= link_to t("administrate.actions.list"), [namespace, page.resource], class: "button"  %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

AdminFarm/app/views/admin/application/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { "#{t("administrate.actions.show")} #{page.page_title}" } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>
  <div>
    <%= link_to( "#{t("administrate.actions.new")} #{t(page.resource_name.titleize.downcase)}", [:new, namespace, page.resource_path], class: "button new") if valid_action? :new %>
    <%= link_to( "#{t("administrate.actions.edit")} #{page.page_title}", [:edit, namespace, page.resource], class: "button edit") if valid_action? :edit %>
    <%= link_to( "#{t("administrate.actions.destroy")} #{page.page_title}", [namespace, page.resource], class: "button delete", method: :delete, data: { confirm: t("administrate.actions.confirm") }) %>
    <%= link_to t("administrate.actions.list"), [namespace, page.resource.class], class: "button"  %>
  </div>
</header>

<% if defined? page.show_page_actions != nil %>
  <%= t("administrate.filter.actions") %>:
  <% page.show_page_actions.each do |key, value| %>
    <%= link_to( "#{t("administrate.actions.new")} #{t(value['model'])}", {:controller => 'admin/'+ value['link'],:action => "new", value['parameter_name'] => page.attributes[value['position_field']]}, {class: "button new button_#{page.attributes[value['position_field']]}"}, ) if valid_action? :new %>
  <% end %>
<% end %>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t( "helpers.label.#{resource_name}.#{attribute.name}", default: attribute.name.titleize) %>
      </dt>
      <dd class="attribute-data attribute-data--<%=attribute.html_class%>">
        <%#= render_field attribute %>
        <%= render_field attribute if attribute.html_class != 'boolean'  %>
        <%= t("#{attribute.html_class}.#{attribute}_", default: attribute) if attribute.html_class == 'boolean' %></dd>
    <% end %>
  </dl>
</section>

<% if (defined? @table0) && (not @table0.empty?) %>
  <%= render("show_tables", table: @table0, page: page) %>
<% end %>

<% if (defined? @table1) && (not @table1.empty?) %>
  <%= render("show_tables", table: @table1, page: page) %>
<% end %>

<% if (defined? @table2) && (not @table2.empty?) %>
  <%= render("show_tables", table: @table2, page: page) %>
<% end %>

<% if (defined? @table3) && (not @table3.empty?) %>
  <%= render("show_tables", table: @table3, page: page) %>
<% end %>

<% if (defined? @table4) && (not @table4.empty?) %>
  <%= render("show_tables", table: @table4, page: page) %>
<% end %>

<% if (defined? @table5) && (not @table5.empty?) %>
  <%= render("show_tables", table: @table5, page: page) %>
<% end %>

<% if (defined? @table6) && (not @table6.empty?) %>
  <%= render("show_tables", table: @table6, page: page) %>
<% end %>